name: Ci/CD

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

jobs:
 build:
   name: Build and create Docker image
   runs-on: ubuntu-latest
   permissions:
     contents: read

   steps:
     - uses: actions/checkout@v4
     - name: Download java v17
       uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'

     - name: Permission settings
       run: chmod +x ./gradlew

     - name: Build
       run: ./gradlew build

     - name: Docker Login
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKERHUB_ID }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}


     - name: Create Docker image
       run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server .

     - name: Push Docker image
       run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server

 deploy:
    name: Run
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Run
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.GCP_USERNAME}}
          key: ${{secrets.GCP_PRIVATEKEY}}
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_ID }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/eureka-server
            sudo docker stop eureka
            sudo docker container rm eureka
            sudo docker run -dit -p 8761:8761 --name eureka ${{secrets.DOCKERHUB_USERNAME}}/eureka-server
            sudo docker image prune -f